// <auto-generated />
using System;
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS4090Project.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Db.Attendance", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Db.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaysOfTheWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstPossibleDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPossibleDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Mask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Privacy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ec07ab7-5385-475c-b727-3bf5beda74ed"),
                            DaysOfTheWeek = false,
                            Description = "Test Description",
                            FirstPossibleDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastPossibleDate = new DateTime(1970, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mask = "[]",
                            OrganizerId = new Guid("fc771b9e-2a04-42a6-b73a-714d6ddc3feb"),
                            Privacy = 2,
                            Title = "Test Event"
                        });
                });

            modelBuilder.Entity("Db.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc771b9e-2a04-42a6-b73a-714d6ddc3feb"),
                            Name = "Test User",
                            PasswordHash = "3AA1154717C6DCAA64174FF0394F0D69A7CCA59B2E322C8883E9B7E6FC2D3D048A895858101CA2C281C5483A2B8926C020D1CEB4B74E4B51EE333320E3928390",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("Db.Attendance", b =>
                {
                    b.HasOne("Db.Event", null)
                        .WithMany("Attendance")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Db.User", null)
                        .WithMany("Attendance")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Db.Event", b =>
                {
                    b.HasOne("Db.User", "Organizer")
                        .WithMany("Organizing")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Db.Event", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Db.User", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("Organizing");
                });
#pragma warning restore 612, 618
        }
    }
}
